-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 01:04:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema NullBank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NullBank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NullBank` DEFAULT CHARACTER SET utf8 ;
USE `NullBank` ;

-- -----------------------------------------------------
-- Table `NullBank`.`agencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`agencia` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `salario_montante_total` DECIMAL NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`funcionario` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `cargo` ENUM('gerente', 'atendente', 'caixa') NOT NULL,
  `sexo` ENUM('masculino', 'feminino') NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `salario` DECIMAL NOT NULL,
  `agencia_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionario_agencia1_idx` (`agencia_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_agencia1`
    FOREIGN KEY (`agencia_id`)
    REFERENCES `NullBank`.`agencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`dependentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`dependentes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `parentesco` ENUM('filho', 'conjuge', 'genitor') NOT NULL,
  `idade` INT NOT NULL,
  `funcionario_matricula` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_completo_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_dependentes_funcionario1_idx` (`funcionario_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_dependentes_funcionario1`
    FOREIGN KEY (`funcionario_matricula`)
    REFERENCES `NullBank`.`funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`cliente` (
  `cpf` INT(11) UNSIGNED NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `RG` VARCHAR(15) NOT NULL,
  `orgao_emissor` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`conta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`conta` (
  `numero` INT UNSIGNED NOT NULL,
  `saldo` DECIMAL NOT NULL,
  `agencia_id` INT UNSIGNED NOT NULL,
  `funcionario_matricula` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_conta_agencia1_idx` (`agencia_id` ASC) VISIBLE,
  INDEX `fk_conta_funcionario1_idx` (`funcionario_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_conta_agencia1`
    FOREIGN KEY (`agencia_id`)
    REFERENCES `NullBank`.`agencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conta_funcionario1`
    FOREIGN KEY (`funcionario_matricula`)
    REFERENCES `NullBank`.`funcionario` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`cliente_telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`cliente_telefones` (
  `telefone` INT(11) NOT NULL,
  `cliente_cpf` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`telefone`, `cliente_cpf`),
  INDEX `fk_cliente_telefones_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_telefones_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `NullBank`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`cliente_email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`cliente_email` (
  `email` VARCHAR(60) NOT NULL,
  `cliente_cpf` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`email`, `cliente_cpf`),
  INDEX `fk_cliente_email_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_email_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `NullBank`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`conta_poupanca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`conta_poupanca` (
  `taxa de juros` INT NOT NULL,
  `conta_numero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`conta_numero`),
  CONSTRAINT `fk_conta_poupanca_conta1`
    FOREIGN KEY (`conta_numero`)
    REFERENCES `NullBank`.`conta` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`conta_corrente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`conta_corrente` (
  `dt_contrato` DATE NOT NULL,
  `conta_numero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`conta_numero`),
  CONSTRAINT `fk_conta_corrente_conta1`
    FOREIGN KEY (`conta_numero`)
    REFERENCES `NullBank`.`conta` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`conta_especial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`conta_especial` (
  `limite_credito` DECIMAL NOT NULL,
  `conta_numero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`conta_numero`),
  CONSTRAINT `fk_conta_especial_conta1`
    FOREIGN KEY (`conta_numero`)
    REFERENCES `NullBank`.`conta` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`endereco` (
  `cliente_cpf` INT(11) UNSIGNED NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `CEP` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `enderecocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cliente_cpf`),
  CONSTRAINT `fk_endereco_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `NullBank`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`possui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`possui` (
  `cliente_cpf` INT(11) UNSIGNED NOT NULL,
  `conta_numero` INT UNSIGNED NOT NULL,
  `conta_conjunta` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cliente_cpf`, `conta_numero`),
  INDEX `fk_cliente_has_conta_conta1_idx` (`conta_numero` ASC) VISIBLE,
  INDEX `fk_cliente_has_conta_cliente1_idx` (`cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_conta_cliente1`
    FOREIGN KEY (`cliente_cpf`)
    REFERENCES `NullBank`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_conta_conta1`
    FOREIGN KEY (`conta_numero`)
    REFERENCES `NullBank`.`conta` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NullBank`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NullBank`.`transacao` (
  `numero` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `transacaocol` ENUM('saque', 'deposito', 'pagamento', 'estorno', 'transferencia') NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `valor` DECIMAL NOT NULL,
  `conta_numero` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_transacao_conta1_idx` (`conta_numero` ASC) VISIBLE,
  CONSTRAINT `fk_transacao_conta1`
    FOREIGN KEY (`conta_numero`)
    REFERENCES `NullBank`.`conta` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
